cc_test (
    name = "loader_test",
    srcs = [
        "LoaderTest.cpp",
    ],
    copts = [
        "-Iexternal/gtest/include",
    ],
    deps = [
        "@gtest//:gtest",
        "//loader:loader",
    ],
)
